<%
out.println("<!DOCTYPE html>");
out.println("<html style=\"font-size: 16px;\">");
out.println("  <head>");
out.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
out.println("    <meta charset=\"utf-8\">");
out.println("    <meta name=\"keywords\" content=\"\">");
out.println("    <meta name=\"description\" content=\"\">");
out.println("    <meta name=\"page_type\" content=\"np-template-header-footer-from-plugin\">");
out.println("    <title>User</title>");
out.println("    <link rel=\"stylesheet\" href=\"nicepage.css\" media=\"screen\">");
out.println("<link rel=\"stylesheet\" href=\"User.css\" media=\"screen\">");
out.println("    <script class=\"u-script\" type=\"text/javascript\" src=\"jquery.js\" defer=\"\"></script>");
out.println("    <script class=\"u-script\" type=\"text/javascript\" src=\"nicepage.js\" defer=\"\"></script>");
out.println("    <meta name=\"generator\" content=\"Nicepage 4.0.3, nicepage.com\">");
out.println("    <link id=\"u-theme-google-font\" rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i\">");
out.println("    ");
out.println("    ");
out.println("    <script type=\"application/ld+json\">{");
out.println("		\"@context\": \"http://schema.org\",");
out.println("		\"@type\": \"Organization\",");
out.println("		\"name\": \"\",");
out.println("		\"logo\": \"images/image-removebg-preview.png\"");
out.println("}</script>");
out.println("    <meta name=\"theme-color\" content=\"#478ac9\">");
out.println("    <meta property=\"og:title\" content=\"User\">");
out.println("    <meta property=\"og:type\" content=\"website\">");
out.println("  </head>");
out.println("  <body class=\"u-body\"><header class=\"u-clearfix u-header u-header\" id=\"sec-59b5\"><div class=\"u-clearfix u-sheet u-valign-top-lg u-valign-top-md u-valign-top-sm u-valign-top-xs u-sheet-1\">");
out.println("        <a href=\"Home.html\" data-page-id=\"62352257\" class=\"u-image u-logo u-image-1\" data-image-width=\"196\" data-image-height=\"109\" title=\"Home\">");
out.println("          <img src=\"images/image-removebg-preview.png\" class=\"u-logo-image u-logo-image-1\">");
out.println("        </a>");
out.println("        <nav class=\"u-menu u-menu-dropdown u-offcanvas u-menu-1\">");
out.println("          <div class=\"menu-collapse\" style=\"font-size: 1rem; letter-spacing: 0px;\">");
out.println("            <a class=\"u-button-style u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base\" href=\"#\">");
out.println("              <svg><use xmlns:xlink=\"http://www.w3.org/1999/xlink\" xlink:href=\"#menu-hamburger\"></use></svg>");
out.println("              <svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"><defs><symbol id=\"menu-hamburger\" viewBox=\"0 0 16 16\" style=\"width: 16px; height: 16px;\"><rect y=\"1\" width=\"16\" height=\"2\"></rect><rect y=\"7\" width=\"16\" height=\"2\"></rect><rect y=\"13\" width=\"16\" height=\"2\"></rect>");
out.println("</symbol>");
out.println("</defs></svg>");
out.println("            </a>");
out.println("          </div>");
out.println("          <div class=\"u-custom-menu u-nav-container\">");
out.println("            <ul class=\"u-nav u-unstyled u-nav-1\"><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base\" href=\"http://127.0.0.1:5500/Home.html\" style=\"padding: 10px 20px;\">Home</a>");
out.println("</li><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base\" href=\"http://127.0.0.1:5500/Donate.html\" style=\"padding: 10px 20px;\">Donate</a>");
out.println("</li><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base\" href=\"http://127.0.0.1:5500/Report.html\" style=\"padding: 10px 20px;\">Report</a>");
out.println("</li><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base\" href=\"http://127.0.0.1:5500/Contact.html\" style=\"padding: 10px 20px;\">Contact</a>");
out.println("</li><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base\" href=\"http://127.0.0.1:5500/User.html\" style=\"padding: 10px 20px;\">User</a>");
out.println("</li></ul>");
out.println("          </div>");
out.println("          <div class=\"u-custom-menu u-nav-container-collapse\">");
out.println("            <div class=\"u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav\">");
out.println("              <div class=\"u-inner-container-layout u-sidenav-overflow\">");
out.println("                <div class=\"u-menu-close\"></div>");
out.println("                <ul class=\"u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2\"><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"http://127.0.0.1:5500/Home.html#\" style=\"padding: 10px 20px;\">Home</a>");
out.println("</li><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"http://127.0.0.1:5500/Donate.html\" style=\"padding: 10px 20px;\">Donate</a>");
out.println("</li><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"http://127.0.0.1:5500/Report.html\" style=\"padding: 10px 20px;\">Report</a>");
out.println("</li><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"http://127.0.0.1:5500/Contact.html\" style=\"padding: 10px 20px;\">Contact</a>");
out.println("</li><li class=\"u-nav-item\"><a class=\"u-button-style u-nav-link\" href=\"http://127.0.0.1:5500/User.html\" style=\"padding: 10px 20px;\">User</a>");
out.println("</li></ul>");
out.println("              </div>");
out.println("            </div>");
out.println("            <div class=\"u-black u-menu-overlay u-opacity u-opacity-70\"></div>");
out.println("          </div>");
out.println("        </nav>");
out.println("      </div></header>");
out.println("    <section class=\"u-align-center u-clearfix u-section-1\" id=\"sec-27d4\">");
out.println("      <div class=\"u-clearfix u-sheet u-sheet-1\">");
out.println("        <div class=\"u-form u-login-control u-form-1\">");
out.println("          <form action=\"#\" method=\"POST\" class=\"u-clearfix u-form-custom-backend u-form-spacing-10 u-form-vertical u-inner-form\" source=\"custom\" name=\"form\" style=\"padding: 10px;\">");
out.println("            <div class=\"u-form-group u-form-name\">");
out.println("              <label for=\"username-a30d\" class=\"u-label\">Username *</label>");
out.println("              <input type=\"text\" placeholder=\"Enter your Username\" id=\"username-a30d\" name=\"username\" class=\"u-grey-5 u-input u-input-rectangle u-input-1\" required=\"\">");
out.println("            </div>");
out.println("            <div class=\"u-form-group u-form-password\">");
out.println("              <label for=\"password-a30d\" class=\"u-label\">Password *</label>");
out.println("              <input type=\"text\" placeholder=\"Enter your Password\" id=\"password-a30d\" name=\"password\" class=\"u-grey-5 u-input u-input-rectangle u-input-2\" required=\"\">");
out.println("            </div>");
out.println("            <div class=\"u-form-checkbox u-form-group\">");
out.println("              <input type=\"checkbox\" id=\"checkbox-a30d\" name=\"remember\" value=\"On\">");
out.println("              <label for=\"checkbox-a30d\" class=\"u-label\">Remember me</label>");
out.println("            </div>");
out.println("            <div class=\"u-align-left u-form-group u-form-submit\">");
out.println("              <a href=\"#\" class=\"u-btn u-btn-submit u-button-style u-btn-1\">Login</a>");
out.println("              <input type=\"submit\" value=\"submit\" class=\"u-form-control-hidden\">");
out.println("            </div>");
out.println("            <input type=\"hidden\" value=\"\" name=\"recaptchaResponse\">");
out.println("          </form>");
out.println("        </div>");
out.println("        <a href=\"#\" class=\"u-border-1 u-border-active-palette-2-base u-border-hover-palette-1-base u-btn u-button-style u-login-control u-login-forgot-password u-none u-text-palette-1-base u-btn-2\">Forgot password?</a>");
out.println("        <a href=\"#\" class=\"u-border-1 u-border-active-palette-2-base u-border-hover-palette-1-base u-btn u-button-style u-login-control u-login-create-account u-none u-text-palette-1-base u-btn-3\">Don't have an account?</a>");
out.println("      </div>");
out.println("    </section>");
out.println("    ");
out.println("    ");
out.println("    <footer class=\"u-align-center u-clearfix u-footer u-grey-80 u-footer\" id=\"sec-1117\"><div class=\"u-clearfix u-sheet u-valign-middle u-sheet-1\">");
out.println("        <p class=\"u-small-text u-text u-text-variant u-text-1\">SAVING-FOOD&nbsp;© 2021</p>");
out.println("      </div></footer>");
out.println("  </body>");
out.println("</html>");
%>